export const GET_HORSE_PROFILE = "GET_HORSE_PROFILE" as const;
export const GET_HORSE_PROFILE_ENTITY = {
  SUCCESS: "GET_HORSE_PROFILE_SUCCESS",
  REQUEST: "GET_HORSE_PROFILE_REQUEST",
  FAILURE: "GET_HORSE_PROFILE_FAILURE"
} as const;
